Repository oracle/oracle-db-appdev-monitoring, pull requests merged in 2024-09, with the labels that each got.

#116 Use go:embed for default metrics
  collector/default_metrics.go
  collector/default_metrics.toml
  go.mod
  go.sum
Labels: OCA Verified

#117 Document multiple custom metrics files
  README.md
  main.go
Labels: OCA Verified

#118 Add Query Timeout to metrics definition
  README.md
  collector/collector.go
  collector/metrics.go
Labels: OCA Verified

#119 Scrape interval per metric
  README.md
  collector/collector.go
  collector/metrics.go
  main.go
Labels: OCA Verified

#121 updates for 1.4.0
  Dockerfile
  Makefile
  README.md
  docker-compose/compose.yaml
  docker-compose/exporter/more-txeventq-metrics.toml
  docker-compose/exporter/txeventq-metrics.toml
  docker-compose/txeventq-load/src/main/resources/application.yaml
Labels: OCA Verified

#123 Release 1.5.0
  Dockerfile
  Makefile
  README.md
  doc/oracledb-dashboard.png
  docker-compose/compose.yaml
  docker-compose/oracle/grant_permissions.sql
  docker-compose/txeventq-load/src/main/resources/application.yaml
  go.mod
  go.sum
Labels: OCA Verified

#127 preparing for 1.5.0 release
  Makefile
  README.md
Labels: OCA Verified

#128 Standalone, spelling and linting
  README.md
Labels: documentation, OCA Verified

#131 OCI Vault fix
  README.md
  main.go
  vault/vault.go
Labels: bug, OCA Verified
